#define PROGRESSION_OUT stdout
#define PROGRESSION

#define PRINTN_PROGRESSION(line) \
    PRINT_TIME_KEEPING(PROGRESSION_OUT, FORE_RACE_TIME_KEEPING) \
    fprintf(PROGRESSION_OUT, FORE_RACE_TIME_KEEPING "● %s" FORE_RESET, line);
